### ISSUE TITLE
v0.3.0 not working

### ISSUE THREAD

**Issue by huczk** [vueneue/vueneue#4] opened 2018-07-17 19:48 UTC
In new plugin version after `yarn ssr:serve` command, there is only info about internal server error, not my app. Error in console:
```
[Vue warn]: Error in beforeCreate hook: "TypeError: this._router.init is not a function"

(found in <Root>)
TypeError: this._router.init is not a function
    at Vue.beforeCreate (/Users/hubertkazmierczak/data/test/base22/test/node_modules/vue-router/dist/vue-router.common.js:542:22)
    at callHook (/Users/hubertkazmierczak/data/test/base22/test/node_modules/vue/dist/vue.runtime.common.js:2919:21)
    at Vue._init (/Users/hubertkazmierczak/data/test/base22/test/node_modules/vue/dist/vue.runtime.common.js:4624:5)
    at new Vue (/Users/hubertkazmierczak/data/test/base22/test/node_modules/vue/dist/vue.runtime.common.js:4727:8)
    at __webpack_exports__.default (webpack-internal:///./src/main.js:12:10)
    at _callee$ (webpack-internal:///./node_modules/@vueneue/ssr-core/server/index.js:39:87)
    at tryCatch (/Users/hubertkazmierczak/data/test/base22/test/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/hubertkazmierczak/data/test/base22/test/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/hubertkazmierczak/data/test/base22/test/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (webpack-internal:///./node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:12:30)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:27:9)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:34:7)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:7:12)
    at eval (webpack-internal:///./node_modules/@vueneue/ssr-core/server/index.js:62:17)
    at /Users/hubertkazmierczak/data/test/base22/test/node_modules/vue-server-renderer/build.js:8426:15
```

With command `yarn serve` there is some other error:
```
Uncaught (in promise) TypeError: Object(...) is not a function
    at __webpack_exports__.default (createContext.js?4427:8)
    at _callee$ (index.js?40a1:15)
    at tryCatch (runtime.js?96cf:62)
    at Generator.invoke [as _invoke] (runtime.js?96cf:296)
    at Generator.prototype.(:8083/anonymous function) [as next] (webpack-internal:///./node_modules/regenerator-runtime/runtime.js:114:21)
    at step (asyncToGenerator.js?3040:10)
    at _next (asyncToGenerator.js?3040:25)
    at eval (asyncToGenerator.js?3040:32)
    at new Promise (<anonymous>)
    at eval (asyncToGenerator.js?3040:5)
```

**Comment by chymz** [comment] 2018-07-17 20:12
Sorry Im not able to reproduce your error, can you share more infos (OS, node version, npm/yarn version, Vue CLI version) ? A simple way to reproduce it ?

Thanks

**Comment by chymz** [comment] 2018-07-17 20:23
Oh, did you create your project without Vue Router and Vuex ? If so, there is a bug in the plugin generator, I will publish a fix tomorrow!

**Comment by huczk** [comment] 2018-07-18 06:04
After created new vue-cli project with vuex and router, `yarn ssr:serve` seems to work. Unfortunetly `yarn serve` still has the same error.
Informations:
- macos
- vue-cli 3.0.0-rc.5
- yarn - 1.8.0
- node - 10.6.0

**Comment by germsb** [comment] 2018-07-18 07:41
I also have an error with ssr:serve.  
I built the project with vue UI. Options are: router, vuex, css-preprocessors -> i18n plugin -> srr plugin.

* windows 10
* vue-cli 3 rc5
* npm 6.1.0
* node 10.5.0

Your plugin look awesome, great job!

```$ vue-cli-service ssr:serve --mode development --host localhost --port 3000 --dashboard
(node:14780) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

[09:18:10] Compiling Client

[09:18:10] Compiling Server

[09:18:11] Compiled Client in 790ms

 DONE  Compiled successfully in 803ms09:18:11


[09:18:12] Compiled Server in 1s

 DONE  Compiled successfully in 1383ms09:18:12

Server started at http://localhost:3000

TypeError: Object(...) is not a function
    at __webpack_exports__.default.ssrContext (webpack-internal:///./node_modules/@vueneue/ssr-core/utils/createContext.js:16:81)
    at __webpack_exports__.default (webpack-internal:///./node_modules/@vueneue/ssr-core/server/index.js:20:87)
    at C:\dev\new\node_modules\vue-server-renderer\build.js:8426:15
    at new Promise (<anonymous>)
    at C:\dev\new\node_modules\vue-server-renderer\build.js:8388:14
    at Object.renderToString (C:\dev\new\node_modules\vue-server-renderer\build.js:8564:9)
    at Promise (C:\dev\new\node_modules\@vueneue\ssr-server\lib\renderRoute.js:8:28)
    at new Promise (<anonymous>)
    at module.exports (C:\dev\new\node_modules\@vueneue\ssr-server\lib\renderRoute.js:4:10)
    at readyPromise.then (C:\dev\new\node_modules\@vueneue\ssr-server\lib\index.js:68:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)


  Error: non-error thrown: {"request":{"method":"GET","url":"/","header":{"host":"localhost:3000","connection":"keep-alive","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","referer":"http://localhost:8000/tasks/C:%5Cdev%5Cnew:ssr:serve","accept-encoding":"gzip, deflate, br","accept-language":"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,la;q=0.6"}},"response":{"status":500,"message":"Internal Server Error","header":{"content-type":"text/html","content-length":"7"}},"app":{"subdomainOffset":2,"proxy":false,"env":"development"},"originalUrl":"/","req":"<original node req>","res":"<original node res>","socket":"<original node socket>"}
      at Object.onerror (C:\dev\new\node_modules\koa\lib\context.js:112:40)
      at onerror (C:\dev\new\node_modules\koa\lib\application.js:148:32)
      at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by chymz** [comment] 2018-07-18 07:49
@huczk & @germsb : I've published `0.3.1` can you test it ?

**Comment by chymz** [comment] 2018-07-18 07:56
Also check you `src/main.js` file have this code:

```js
export default ({ router, store }) => {
  return new Vue({
    router,
    store,
    render: h => h(App),
  });
};
```

**Comment by germsb** [comment] 2018-07-18 08:05
After build a new project, i get the same error. 
`src/main.js` 
```
export default ({ router, store }) => {
  return new Vue({
    router,
    store,
    i18n: createI18n(),
    render: h => h(App)
  });
}
```

**Comment by germsb** [comment] 2018-07-18 08:15
With  the serve script, I can see this [error](https://i.imgur.com/wmQlF0A.png) in the brother

**Comment by huczk** [comment] 2018-07-18 08:16
Mine application now working exclude `yarn ssr:start` after `ssr:build`. Only main and vendor scripts are fetched by the browser. In the console is error:
```
main.f9ee91b3.js:formatted:46 Uncaught TypeError: Cannot read property 'call' of undefined
    at c (main.f9ee91b3.js:formatted:46)
    at r (main.f9ee91b3.js:formatted:22)
    at +wUL (main.f9ee91b3.js:formatted:165)
    at main.f9ee91b3.js:formatted:167
```

**Comment by chymz** [comment] 2018-07-18 08:16
Can you put your code in a github repository ? Thanks !

**Comment by chymz** [comment] 2018-07-18 08:29
@huczk : I'm able to reproduce your error, I'm working on it
@germsb : It's look like you still use old version of this plugin, can you share your code ?

**Comment by germsb** [comment] 2018-07-18 08:34
https://github.com/germsb/testssr

**Comment by chymz** [comment] 2018-07-18 08:57
@germsb Windows problem, working on it too

**Comment by chymz** [comment] 2018-07-18 13:53
I think I've fixed your issues. Can you try `0.3.2` ?

**Comment by huczk** [comment] 2018-07-18 17:18
Yes, my project working except: with ssr:start after ssr:build - service-worker is not loaded. With spa commands there is no errors.
Any way, huge thanks for your work, plugin and very fast reaction :)

**Comment by huczk** [comment] 2018-07-18 17:48
Here is the code: https://github.com/huczk/ssr-test

**Comment by chymz** [comment] 2018-07-18 21:15
`Uncaught TypeError: Cannot read property 'call' of undefined` fixed in `0.3.3` :smile: 

Thanks for giving your time guys !

**Closed by chymz** 2018-07-18 21:15 UTC
Labels: bug, feat: generator

**Comment by camwhite** [comment] 2018-07-18 22:53
Hey was experiencing  `Uncaught TypeError: Cannot read property 'call' of undefined` after build and have upgraded to `0.3.3`. Now when I serve i see this error...

```
TypeError: Object(...) is not a function
    at _callee$ (webpack-internal:///./node_modules/@vueneue/ssr-core/server/index.js:35:87)
    at tryCatch (/home/cam/code/givii-web/frontend/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/cam/code/givii-web/frontend/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/cam/code/givii-web/frontend/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (webpack-internal:///./node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:12:30)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:27:9)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:34:7)
    at new Promise (<anonymous>)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:7:12)
    at eval (webpack-internal:///./node_modules/@vueneue/ssr-core/server/index.js:58:17)
    at /home/cam/code/givii-web/frontend/node_modules/vue-server-renderer/build.js:8426:15
    at new Promise (<anonymous>)
    at /home/cam/code/givii-web/frontend/node_modules/vue-server-renderer/build.js:8388:14
    at Object.renderToString (/home/cam/code/givii-web/frontend/node_modules/vue-server-renderer/build.js:8564:9)
    at Promise (/home/cam/code/givii-web/frontend/node_modules/@vueneue/ssr-server/lib/renderRoute.js:8:28)
    at new Promise (<anonymous>)
```

Any help would be appreciated and great job on the package!

**Comment by chymz** [comment] 2018-07-18 22:56
Can you provide more infos ?

You say `serve`: you mean `ssr:serve` ?

Can you provide some code ?

**Comment by camwhite** [comment] 2018-07-18 22:59
Yes sorry `ssr:serve`. To upgrade i bumped the package versions and ran `vue add @vueneue/ssr` again. Could this approach be the problem?

**Comment by chymz** [comment] 2018-07-18 23:01
So you run `vue add @vueneue/ssr` twice ? (one before upgrade, one after)

If, so: check your `src/main.js`, `router.js` and `store.js`: do they export a default function ?

**Comment by camwhite** [comment] 2018-07-18 23:05
`src/main.js` exports two functions `createApp` and `initApp`. Also here is error output after running `ssr:build` and `ssr:start`... 

```
TypeError: A is not a function
    at server-bundle.js:1:380685
    at tryCatch (/home/cam/code/givii-web/frontend/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/home/cam/code/givii-web/frontend/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/home/cam/code/givii-web/frontend/node_modules/regenerator-runtime/runtime.js:114:21)
    at a (node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:20:0)
    at c (node_modules/@babel/runtime/helpers/builtin/es6/asyncToGenerator.js:32:0)
    at server-bundle.js:1:250556
    at new Promise (<anonymous>)
    at server-bundle.js:1:250347
    at server-bundle.js:1:380861
```

**Comment by chymz** [comment] 2018-07-18 23:10
Yeah, my migration guide is a bit light : https://vueneue.github.io/docs/guide/migrate.html#from-0-2-to-0-3

`initApp` was removed and  `createApp` need to be replaced by a default export:

```js
export default ({ router, store }) => {
  return new Vue({
    router,
    store,
    render: h => h(App),
  });
};
```

Like here: https://vueneue.github.io/docs/guide/start.html#base-files-code-structure

**Comment by camwhite** [comment] 2018-07-18 23:18
Awesome working now :D thanks for your help. I'm doing some auth with this plugin. Would it be appropriate to post an issues to critique my approach?

**Comment by chymz** [comment] 2018-07-18 23:21
No problem dude !

**Comment by germsb** [comment] 2018-07-19 16:42
Ok it works! (ssr:serve, v0.33) but I have an issue with the HMR.
```
WebSocket connection to 'ws://0.0.0.0:63782/' failed:
Error in connection establishment: net::ERR_ADDRESS_INVALID
｢hot｣ WebSocket closed 
```
You should perhaps replace 0.0.0.0 by 127.0.0.1

Otherwise, srr:build and ssr:start work fine 
Many thanks for your job

**Comment by chymz** [comment] 2018-07-19 19:56
@germsb Do you use Vue UI? This utility keep your ssr:serve config in localStorage.

127.0.0.1 is the default since #1

**Comment by germsb** [comment] 2018-07-20 12:32
Yes use it, you're right.
